//
// BrandedFoodObjectPackagingPhotos.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A object containing a collection of photos of this item&#x27;s packaging */

public struct BrandedFoodObjectPackagingPhotos: Codable {

    public var front: BrandedFoodObjectPackagingPhotosFront?
    public var nutrition: BrandedFoodObjectPackagingPhotosNutrition?
    public var ingredients: BrandedFoodObjectPackagingPhotosIngredients?

    public init(front: BrandedFoodObjectPackagingPhotosFront? = nil, nutrition: BrandedFoodObjectPackagingPhotosNutrition? = nil, ingredients: BrandedFoodObjectPackagingPhotosIngredients? = nil) {
        self.front = front
        self.nutrition = nutrition
        self.ingredients = ingredients
    }


}
