//
// BrandedFoodObjectDietLabels.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing this item&#x27;s compatibility grades for each supported diet */

public struct BrandedFoodObjectDietLabels: Codable {

    public var vegan: BrandedFoodObjectDietLabelsVegan?
    public var vegetarian: BrandedFoodObjectDietLabelsVegetarian?
    public var glutenFree: BrandedFoodObjectDietLabelsGlutenFree?

    public init(vegan: BrandedFoodObjectDietLabelsVegan? = nil, vegetarian: BrandedFoodObjectDietLabelsVegetarian? = nil, glutenFree: BrandedFoodObjectDietLabelsGlutenFree? = nil) {
        self.vegan = vegan
        self.vegetarian = vegetarian
        self.glutenFree = glutenFree
    }

    public enum CodingKeys: String, CodingKey { 
        case vegan
        case vegetarian
        case glutenFree = "gluten_free"
    }

}
