//
// BrandedFoodObjectPackagingPhotosNutrition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing photos of this item&#x27;s nutrition label */

public struct BrandedFoodObjectPackagingPhotosNutrition: Codable {

    /** Small photo of this item&#x27;s nutrition label */
    public var small: String?
    /** Thumbnail photo of this item&#x27;s nutrition label */
    public var thumb: String?
    /** Full-sized photo of this item&#x27;s nutrition label */
    public var display: String?

    public init(small: String? = nil, thumb: String? = nil, display: String? = nil) {
        self.small = small
        self.thumb = thumb
        self.display = display
    }


}
