//
// BrandedFoodObjectDietLabelsGlutenFree.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing information on this item&#x27;s compatibility with Gluten Free diets */

public struct BrandedFoodObjectDietLabelsGlutenFree: Codable {

    /** Diet name */
    public var name: String?
    /** Boolean describing if this item is compatible with this diet */
    public var isCompatible: Bool?
    /** Numeric representation of how compatible this item is with this diet. Higher values indicate more compatibility */
    public var compatibilityLevel: Int?
    /** Boolean that indicates if we are confident in how this item is graded for this diet */
    public var confidence: Int?
    /** Description of our confidence that this item was graded correctly */
    public var confidenceDescription: String?

    public init(name: String? = nil, isCompatible: Bool? = nil, compatibilityLevel: Int? = nil, confidence: Int? = nil, confidenceDescription: String? = nil) {
        self.name = name
        self.isCompatible = isCompatible
        self.compatibilityLevel = compatibilityLevel
        self.confidence = confidence
        self.confidenceDescription = confidenceDescription
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case isCompatible = "is_compatible"
        case compatibilityLevel = "compatibility_level"
        case confidence
        case confidenceDescription = "confidence_description"
    }

}
