//
// IngredientObjectNutrients.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing information for a specific nutrient found in this food item */

public struct IngredientObjectNutrients: Codable {

    /** Nutrient name */
    public var name: String?
    /** Amount of the nutrient per 100g of food */
    public var per100g: Decimal?
    /** The unit used for the measure of this nutrient */
    public var measurementUnit: String?
    /** Minimum nutrient value */
    public var min: Decimal?
    /** Maximum nutrient value */
    public var max: Decimal?
    /** Median nutrient value */
    public var median: Decimal?
    /** Nutrient rank */
    public var rank: Int?
    /** Number of observations on which the value is based */
    public var dataPoints: Int?
    /** Comments on any unusual aspect of the food nutrient. Examples might include why a nutrient value is different than typically expected. */
    public var footnote: String?
    /** Description of the nutrient source */
    public var _description: String?

    public init(name: String? = nil, per100g: Decimal? = nil, measurementUnit: String? = nil, min: Decimal? = nil, max: Decimal? = nil, median: Decimal? = nil, rank: Int? = nil, dataPoints: Int? = nil, footnote: String? = nil, _description: String? = nil) {
        self.name = name
        self.per100g = per100g
        self.measurementUnit = measurementUnit
        self.min = min
        self.max = max
        self.median = median
        self.rank = rank
        self.dataPoints = dataPoints
        self.footnote = footnote
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case per100g = "per_100g"
        case measurementUnit = "measurement_unit"
        case min
        case max
        case median
        case rank
        case dataPoints = "data_points"
        case footnote
        case _description = "description"
    }

}
