//
// IngredientObjectComponents.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing information on a specific component of this food item */

public struct IngredientObjectComponents: Codable {

    /** The kind of component, e.g. bone */
    public var name: String?
    /** The weight of the component as a percentage of the total weight of the food */
    public var pctWeight: Decimal?
    /** The weight of the component in grams */
    public var gramWeight: Decimal?
    /** Whether the component is refuse, i.e. not edible */
    public var isRefuse: Bool?
    /** The number of obersvations on which the measure is based */
    public var dataPoints: Int?

    public init(name: String? = nil, pctWeight: Decimal? = nil, gramWeight: Decimal? = nil, isRefuse: Bool? = nil, dataPoints: Int? = nil) {
        self.name = name
        self.pctWeight = pctWeight
        self.gramWeight = gramWeight
        self.isRefuse = isRefuse
        self.dataPoints = dataPoints
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case pctWeight = "pct_weight"
        case gramWeight = "gram_weight"
        case isRefuse = "is_refuse"
        case dataPoints = "data_points"
    }

}
