//
// IngredientObjectPortions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing information on a specific food portion found in this item */

public struct IngredientObjectPortions: Codable {

    /** The unit used for measure (e.g. if mesure is 3 tsp, the unit is tsp) */
    public var measurementUnit: String?
    /** Comments that provide more specificity on the measure. For example, for a pizza measure the dissemination text might be 1 slice is 1/8th of a 14 inch pizza. */
    public var _description: String?
    /** Qualifier of the measure (e.g. related to food shape or form) (e.g. melted, crushed, diced) */
    public var modifier: String?
    /** The weight of the measure in grams */
    public var gramWeight: Decimal?
    /** The number of observations on which the measure is based */
    public var dataPoints: Int?
    /** Comments on any unusual aspects of the measure. Examples might includes caveats on the usage of a measure, or reasons why a measure gram weight is an unexpected value. */
    public var footnote: String?

    public init(measurementUnit: String? = nil, _description: String? = nil, modifier: String? = nil, gramWeight: Decimal? = nil, dataPoints: Int? = nil, footnote: String? = nil) {
        self.measurementUnit = measurementUnit
        self._description = _description
        self.modifier = modifier
        self.gramWeight = gramWeight
        self.dataPoints = dataPoints
        self.footnote = footnote
    }

    public enum CodingKeys: String, CodingKey { 
        case measurementUnit = "measurement_unit"
        case _description = "description"
        case modifier
        case gramWeight = "gram_weight"
        case dataPoints = "data_points"
        case footnote
    }

}
