//
// RecipeObjectNutrients.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing nutrient information for this recipe */

public struct RecipeObjectNutrients: Codable {

    /** An array containing information for calories found in this recipe */
    public var calories: [RecipeObjectNutrientsCalories]?
    /** An array containing information for this recipe&#x27;s daily recommended value of certain nutrients */
    public var dailyValues: [RecipeObjectNutrientsCalories]?
    /** An array containing information for fat found in this recipe */
    public var fat: [RecipeObjectNutrientsCalories]?
    /** An array containing information for carbs found in this recipe */
    public var carbs: [RecipeObjectNutrientsCalories]?
    /** An array containing information for vitamins found in this recipe */
    public var vitamins: [RecipeObjectNutrientsCalories]?

    public init(calories: [RecipeObjectNutrientsCalories]? = nil, dailyValues: [RecipeObjectNutrientsCalories]? = nil, fat: [RecipeObjectNutrientsCalories]? = nil, carbs: [RecipeObjectNutrientsCalories]? = nil, vitamins: [RecipeObjectNutrientsCalories]? = nil) {
        self.calories = calories
        self.dailyValues = dailyValues
        self.fat = fat
        self.carbs = carbs
        self.vitamins = vitamins
    }

    public enum CodingKeys: String, CodingKey { 
        case calories
        case dailyValues = "daily_values"
        case fat
        case carbs
        case vitamins
    }

}
