//
// RecipeObjectAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing recipe attributes */

public struct RecipeObjectAttributes: Codable {

    /** The time it takes to prep this recipe */
    public var prepTime: String?
    /** The total time it takes to make this recipe */
    public var totalTime: String?
    /** The number of servings this recipe makes */
    public var servings: String?
    /** The size of each serving */
    public var servingSize: String?

    public init(prepTime: String? = nil, totalTime: String? = nil, servings: String? = nil, servingSize: String? = nil) {
        self.prepTime = prepTime
        self.totalTime = totalTime
        self.servings = servings
        self.servingSize = servingSize
    }

    public enum CodingKeys: String, CodingKey { 
        case prepTime = "prep_time"
        case totalTime = "total_time"
        case servings
        case servingSize = "serving_size"
    }

}
