//
// RecipeObjectIngredients.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object containing information about a specific recipe ingredient */

public struct RecipeObjectIngredients: Codable {

    /** The quantity of this ingredient */
    public var quantity: String?
    /** A description of this ingredient */
    public var _description: String?

    public init(quantity: String? = nil, _description: String? = nil) {
        self.quantity = quantity
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case quantity
        case _description = "description"
    }

}
