//
// RecipeObjectNutrientsCalories.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RecipeObjectNutrientsCalories: Codable {

    /** Nutrient name */
    public var title: String?
    /** The amount of this nutrient in this recipe */
    public var value: String?
    /** The daily recommended percent total for this nutrient */
    public var percent: String?

    public init(title: String? = nil, value: String? = nil, percent: String? = nil) {
        self.title = title
        self.value = value
        self.percent = percent
    }


}
